version: 2
jobs:
  build:
    docker:
      - image: nrel/openstudio:2.8.1
    steps:
      - checkout
      - run: 
          name: Install gems
          command: |
            gem install nokogiri && gem install codecov
      - run:
          name: Update measure
          command: |
            rake update_measures
      - run: 
          name: Run tests
          command: |
            ruby tests/hpxml_translator_test.rb
      - store_artifacts:
          path: tests/results
          destination: results
