version: 2
jobs:
  build:
    docker:
      - image: nrel/openstudio:2.9.0
    steps:
      - checkout
      - run:
          name: Install gems
          command: |
            rm -f Gemfile.lock && bundle install
      - run:
          name: Update measure
          command: |
            rake update_measures
      - run:
          name: Run tests
          command: |
            openstudio workflow/tests/energy_rating_index_test.rb --name=test_sample_files
      - store_artifacts:
          path: workflow/tests/test_results
          destination: results
      - store_artifacts:
          path: workflow/tests/test_files/sample_files/base-location-dallas-tx.xml
          destination: test_results
      - store_artifacts:
          path: workflow/sample_files/base-location-dallas-tx.xml
          destination: base-location-dallas-tx.xml
      - store_artifacts:
          path: measures
