version: 2
jobs:
  build:
    docker:
      - image: nrel/openstudio:2.9.1
    steps:
      - checkout
      - run:
          name: Install gems
          command: |
            rm -f Gemfile.lock && bundle install
      - run:
          name: Run ruleset tests
          command: |
            for file in `ls rulesets/*/tests/*.rb`; do ruby $file; done
      - run:
          name: Run workflow tests
          command: |
            for file in `ls workflow/tests/*.rb`; do ruby $file; done
      - store_artifacts:
          path: workflow/tests/test_results
          destination: results
